name: elastic_dart
version: 0.2.3
description: An Elasticsearch connector for Dart
homepage: https://github.com/Pajn/ElasticDart
authors:
- Jesper Håkansson <jesper@jesperh.se>
- Rasmus Eneman <rasmus@eneman.eu>
dependencies:
  http: '>=0.11.1+3 <0.12.0'
  warehouse:
    git: https://github.com/Pajn/Warehouse
dev_dependencies:
  guinness: '>=0.1.17 <0.2.0'
  unittest: '>=0.11.0 <0.12.0'
